swagger: '2.0'
info: {title: sharedmfa, version: '1.0', description: thetanz/sharedmfa}
host: function_url_here
basePath: /api
schemes: [https]
securityDefinitions:
  API Key: {type: apiKey, in: header, name: code}
security:
- API Key: []
paths:
  /add-totp-secret:
    post:
      description: recieve QR data for new applications {"data": "totp://xxxxxxx"}
      operationId: add
      summary: add new multifactor application
      responses:
        '200': {description: 'null'}
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          properties:
            data: {type: string, description: data}
  /list-available-apps:
    get:
      description: list all available applications
      operationId: list
      summary: list all available applications
      responses:
        '200': {description: 'null'}
  /get-mfa-code:
    get:
      description: returns MFA code for a given application UUID
      operationId: get
      summary: returns MFA code for a given application UUID
      parameters:
      - {name: uuid, in: query, required: true, type: string}
      responses:
        '200': {description: 'null'}
tags: []
